"use client"
import { createContext, useContext, useState, useEffect } from "react"

export const LanguageContext = createContext()

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

const translations = {
  en: {
    common: {
      loading: "Loading...",
      error: "Error",
      success: "Success",
    },
    cookies: {
      title: "We use cookies",
      message:
        "We use cookies to enhance your browsing experience, serve personalized content, and analyze our traffic. By clicking 'Accept All', you consent to our use of cookies.",
      accept: "Accept All",
      decline: "Decline",
      learnMore: "Learn More",
    },
    welcome: {
      title: "Welcome to Your Health Portal",
      subtitle:
        "Access your appointments, medical records, and manage your healthcare journey with ease and confidence",
    },
    disclaimer: {
      title: "Important Information",
      lines: [
        "PLEASE NOTE THAT THIS IS NOT AN EMERGENCY SERVICE.",
        "In case of an emergency, call 999 (police), 998 (ambulance), or go to the nearest A&E facility.",
        "If you are unable to attend or wish to reschedule, please provide at least 24 hours' notice; otherwise a cancellation fee may apply.",
        "All correspondence is confidential. Please do not disclose your appointment or personal information outside this office.",
        "For in-person appointments, arrive 15 minutes early to complete any necessary paperwork.",
        "If you have insurance, bring your policy details (insurer name, policy number, subscriber ID).",
        "For telemedicine, ensure you have a stable internet connection, a compatible device, and a quiet private space.",
      ],
    },
    services: {
      bookAppointment: {
        title: "Book Appointment",
        description: "Schedule your next appointment with our specialists",
      },
      myProfile: {
        title: "My Profile",
        description: "View and update your personal information",
      },
      myAppointments: {
        title: "My Appointments",
        description: "View your upcoming and past appointments",
      },
      myInvoices: {
        title: "My Invoices",
        description: "Access your billing information and payment history",
      },
    },
    auth: {
      welcomeBack: "Welcome Back",
      createAccount: "Create Account",
      email: "Email Address",
      password: "Password",
      fullName: "Full Name",
      phone: "Phone Number",
      gender: "Gender",
      confirmPassword: "Confirm Password",
      emailPlaceholder: "Enter your email",
      passwordPlaceholder: "Enter your password",
      fullNamePlaceholder: "Enter your full name",
      phonePlaceholder: "Enter your phone number",
      createPasswordPlaceholder: "Create a strong password",
      confirmPasswordPlaceholder: "Confirm your password",
      selectGender: "Select gender",
      male: "Male",
      female: "Female",
      rememberMe: "Remember me for 30 days",
      signIn: "Sign In",
      signingIn: "Signing In...",
      creatingAccount: "Creating Account...",
      noAccount: "Don't have an account? Create one here",
      haveAccount: "Already have an account? Sign in here",
      forgotPassword: "Forgot Password?",
      forgotPasswordTitle: "Forgot Password",
      forgotPasswordSubtitle: "Enter your email to receive a password reset link",
      resetPasswordTitle: "Reset Password",
      resetPasswordSubtitle: "Enter your new password",
      enterYourEmail: "Enter your email",
      sendResetLink: "Send Reset Link",
      sending: "Sending...",
      backToLogin: "Back to Login",
      newPassword: "New Password",
      enterNewPassword: "Enter new password",
      confirmNewPassword: "Confirm new password",
      resetPassword: "Reset Password",
      resetting: "Resetting...",
      passwordMinLength: "Must be at least 8 characters",
      resetSuccess: "Password reset successful! Redirecting to login...",
      resetEmailSent: "Password reset email sent! Please check your inbox.",
      invalidResetLink: "Invalid reset link",
      passwordsDoNotMatch: "Passwords do not match",
      passwordTooShort: "Password must be at least 8 characters long",
      resetFailed: "Failed to reset password",
      sendEmailFailed: "Failed to send reset email",
      errorOccurred: "An error occurred. Please try again.",
    },
    validation: {
      invalidEmail: "Please enter a valid email address",
      passwordTooShort: "Password must be at least 6 characters",
      invalidName: "Name must contain only letters and be at least 2 characters",
      invalidPhone: "Please enter a valid phone number",
      weakPassword: "Password must be at least 8 characters with uppercase, lowercase, and number",
      passwordMismatch: "Passwords do not match",
      validEmail: "Valid email address",
      validName: "Valid name",
      validPhone: "Valid phone number",
      passwordsMatch: "Passwords match",
    },
    messages: {
      logoutSuccess: "Logged out successfully",
      loginSuccess: "Welcome back! Login successful",
      loginFailed: "Login failed",
      signupSuccess: "Registration successful! Please log in with your credentials",
      signupFailed: "Registration failed",
      fixErrors: "Please fix the errors before submitting",
      selectGender: "Please select your gender",
    },
    wizard: {
      bookAppointment: "Book Your Appointment",
      selectEvaluationType: "Select Evaluation Type",
      chooseEvaluationType: "Choose the type of evaluation that best suits your needs",
      evaluationType: "Evaluation Type",
      chooseYourEvaluationType: "Choose your evaluation type...",
      schoolEvaluation: "School Evaluation",
      fullPackageEvaluation: "Full Package Evaluation",
      alreadyActive: "(Already Active)",
      singleSession: "Single Session",
      continue: "Continue →",
      requestEvaluation: "Request Evaluation",
      scheduleAppointment: "Schedule Your Appointment",
      selectPreferredDateTime: "Select your preferred date, time, and provide details",
      selectDay: "Select Day",
      chooseDate: "Choose a date",
      selectTime: "Select Time",
      chooseTime: "Choose a time",
      selectedTime: "Selected time:",
      description: "Description",
      descriptionPlaceholder: "Please describe your needs or any specific requirements...",
      selectServices: "Select Services",
      chooseServices: "Choose your services...",
      selectedServicesTotal: "Selected Services Total:",
      back: "← Back",
      wordDocument: "Word Document",
      reviewEditDocument: "Review & Edit Document",
      reviewCustomizeDocument: "Review and customize your treatment plan document",
      proceedToPayment: "Proceed to Payment →",
      payment: "Payment",
      completePayment: "Complete Payment",
      securePaymentProcessing: "Secure payment processing for your appointment",
      paymentSummary: "Payment Summary",
      fullProgramTotal: "Full Program Total:",
      initialPaymentToday: "Initial Payment (Today):",
      remainingAfterConsultation: "Remaining (After Consultation):",
      payingNow: "Paying Now:",
      paymentNote: "You'll complete the remaining payment after your consultation with the doctor.",
      programFee: "Program Fee:",
      additionalServices: "Additional Services:",
      totalAmount: "Total Amount:",
      completePaymentButton: "💳 Complete Payment",
      processing: "Processing...",
      securePayment: "Secure payment processing • SSL encrypted",
      complete: "Complete",
      congratulations: "Congratulations!",
      appointmentBooked: "Your appointment has been successfully booked at Rukn Elwatikon Rehabilitation Center.",
      schoolEvaluationAssigned: " You have been assigned to our school evaluation program.",
      serviceAssignments: "Service Assignments",
      assignedToServices: "You have been automatically assigned to {count} service(s).",
      whatsNext: "What's Next?",
      nextSteps: [
        "• You'll receive a confirmation email shortly",
        "• Our team will contact you 24 hours before your appointment",
        "• Please arrive 15 minutes early",
        "• You can now access the school evaluation portal",
        "• You can view your service assignments in the respective department portals",
      ],
      validation: {
        selectEvaluationType: "Please select an evaluation type",
        selectDate: "Please select a date",
        selectTime: "Please select a time",
        provideDescription: "Please provide a description",
        selectAtLeastOneService: "Please select at least one service",
      },
    },
    profile: {
      title: "Student Profile",
      loading: "Loading profile...",
      error: "Error loading profile",
      noData: "No profile data available",
      personalInfo: "Personal Information",
      medicalInfo: "Medical Information",
      programs: "Programs",
      schools: "Schools",
      fullProgram: "Full Program",
      singleProgram: "Single Program",
      name: "Name",
      email: "Email",
      phone: "Phone",
      gender: "Gender",
      dateOfBirth: "Date of Birth",
      address: "Address",
      emergencyContact: "Emergency Contact",
      medicalHistory: "Medical History",
      allergies: "Allergies",
      medications: "Current Medications",
      lastVisit: "Last Visit",
      nextAppointment: "Next Appointment",
      programName: "Program",
      upcomingEvaluation: "Upcoming Evaluation Session",
      missedEvaluation: "Missed Evaluation Session",
      evaluationScheduled: "Your evaluation session is scheduled",
      arriveEarly:
        "Please arrive 15 minutes early for your appointment. This session will help us assess your needs and create a personalized program for you.",
      missedSession: "You missed your evaluation session",
      contactReschedule:
        "Please contact us to reschedule your evaluation session. This is important to start your personalized program.",
      programActive: "Your program is now active!",
      accessFiles:
        "You can now access all your files and track your progress. Your evaluation session was completed on",
      initialEvaluation: "Initial Evaluation:",
      programEnded: "This program has ended",
      subscriptionEnded: "Your program subscription ended on",
      stillAccess: "You can still access your files and progress history. Your initial evaluation was completed on",
      files: "files",
      departments: "departments",
      plans: "Plans",
      exams: "Exams",
      viewDocument: "View Document",
      downloadDocument: "Download Document",
      backToFiles: "Back to Files",
      tryAgain: "Try Again",
      programName: "Program",
      programType: "Program Type",
      startDate: "Start Date",
      endDate: "End Date",
      status: "Status",
      progress: "Progress",
      description: "Description",
      instructor: "Instructor",
      duration: "Duration",
      sessions: "Sessions",
      completed: "Completed",
      inProgress: "In Progress",
      upcoming: "Upcoming",
      cancelled: "Cancelled",
      schoolName: "School Name",
      grade: "Grade",
      academicYear: "Academic Year",
      subjects: "Subjects",
      performance: "Performance",
      attendance: "Attendance",
      notes: "Notes",
      noPrograms: "No programs found",
      noSchools: "No schools found",
      viewDetails: "View Details",
      editProfile: "Edit Profile",
      saveChanges: "Save Changes",
      cancel: "Cancel",
      male: "Male",
      female: "Female",
      other: "Other",
      active: "Active",
      inactive: "Inactive",
      excellent: "Excellent",
      good: "Good",
      average: "Average",
      needsImprovement: "Needs Improvement",
      editProfile: "Edit Profile",
      changePassword: "Change Password",
      fullProgram: "Full Program",
      school: "School",
      single: "Single",
      caseStudy: "Case Study",
      manageProfile: "Manage your profile, view evaluations, and track sessions",
      fullName: "Full Name",
      emailAddress: "Email",
      phoneNumber: "Phone Number",
      dateOfBirth: "Date of Birth",
      address: "Address",
      newPassword: "New Password",
      confirmPassword: "Confirm Password",
      enterFullName: "Enter Full Name",
      enterEmail: "Enter email address",
      enterPhone: "Enter phone number",
      enterAddress: "Enter address",
      enterNewPassword: "Enter New Password",
      confirmPasswordPlaceholder: "Confirm Password",
      cancel: "Cancel",
      saveChanges: "Save Changes",
      savePassword: "Save Password",
      student: "Student",
      notProvided: "Not provided",
      required: "*",
      at: "at", // Added for "date at time"
      programId: "Program ID",
      sessionsCompleted: "sessions completed",
      noPlansAvailable: "No Plans Available",
      yourPlanNotCreated: "Your plan didn't created yet",
      plansWillBeAvailableAfterCompletion: "Plans will be available after your program is completed",
      plansWillBeAvailableAfterAllAppointments: "Plans will be available after all appointments are completed",
      plansNotAvailableForCancelled: "Plans are not available for cancelled programs",
      appointments: "Appointments",
      schoolPlans: "School Plans",
      modified: "Modified",
      noSchoolProgramsYet: "You don't have any school programs yet.",
      programScheduledUpcoming: "Program scheduled - First appointment is upcoming",
      programCancelledMissed: "Program cancelled - First appointment was missed",
      programCompletedAllFinished: "Program completed - All appointments finished",
      programActiveNextUpcoming: "Program active - Next appointment is upcoming",
      programActiveNextReady: "Program active - Next appointment is ready",
      programActiveInProgress: "Program active - In progress",
      programStatusUnknown: "Program status unknown",
      noAppointmentsFound: "No appointments found",
      invalidAppointmentDateTime: "Invalid appointment date/time",
      missed: "Missed",
      notStarted: "Not Started",
      unknown: "Unknown",
      backToPrograms: "Back to Programs",
      assignmentDetails: "Assignment Details",
      session: "Session",
      assignedDate: "Assigned Date",
      notes: "Notes",
      treatmentPlan: "Treatment Plan",
      lastUpdated: "Last updated",
      noAssignmentFound: "No assignment found for this department",
      noTreatmentPlanAvailable: "No treatment plan available yet",
      notAssigned: "Not Assigned",
      noSingleProgramsYet: "You don't have any single program appointments yet.",
      of: "of", // Added for "X of Y sessions completed"
      invalidDate: "Invalid Date", // Added for date formatting error
      invalidTime: "Invalid Time", // Added for time formatting error
      noTime: "No time", // Added for missing time
      failedToDownload: "Failed to download file. Please try again.", // Added for download error
      schoolProgram: "School Program", // Added translation for school program title
      openDriveFolder: "Open Drive Folder", // Added translation for drive link button
      noMediaYet: "No media available yet", // Added translation for no media placeholder
      failedToLoadPrograms: "Failed to load single programs. Please try again.",
      abaTherapy: "ABA",
      speechTherapy: "Speech Therapy",
      physicalTherapy: "Physical Therapy",
      occupationalTherapy: "Occupational Therapy",
      specialEducation: "Special Education",
      paidOnline: "Paid Online",
      paidAtCenter: "Paid at Center",
      paidViaBankTransfer: "Paid via Bank Transfer",
      bankTransferPending: "Bank Transfer Pending",
      bankTransferRejected: "Bank Transfer Rejected",
      pendingOnlinePayment: "Pending Online Payment",
      pendingPaymentAtCenter: "Pending Payment at Center",
      paidOnlineViaWebsite: "Paid online via website",
      paidCashAtCenter: "Paid cash at center",
      paidViaBankTransferConfirmed: "Paid via bank transfer (Confirmed)",
      bankTransferPendingMessage: "Your bank transfer is being reviewed. We will notify you once confirmed.",
      bankTransferRejectedMessage: "Your bank transfer payment was rejected. Please contact support.",
      waitingForOnlinePayment: "Waiting for online payment",
      paymentDueAtCenter: "Payment due when client arrives at center",
      completedAt: "Completed:",
      departmentsCount: "departments",
    },
  },
  ar: {
    common: {
      loading: "جاري التحميل...",
      error: "خطأ",
      success: "نجح",
    },
    cookies: {
      title: "نستخدم ملفات تعريف الارتباط",
      message:
        "نستخدم ملفات تعريف الارتباط لتحسين تجربة التصفح الخاصة بك، وتقديم محتوى مخصص، وتحليل حركة المرور لدينا. بالنقر على 'قبول الكل'، فإنك توافق على استخدامنا لملفات تعريف الارتباط.",
      accept: "قبول الكل",
      decline: "رفض",
      learnMore: "معرفة المزيد",
    },
    welcome: {
      title: "مرحباً بك في بوابة الصحة الخاصة بك",
      subtitle: "الوصول إلى مواعيدك والسجلات الطبية إدارة رحلتك الصحية بسهولة وثقة",
    },
    disclaimer: {
      title: "معلومات مهمة",
      lines: [
        "يرجى ملاحظة أن هذه ليست خدمة طوارئ.",
        "في حالة الطوارئ، اتصل بـ 999 (الشرطة)، 998 (الإسعاف)، أو اذهب إلى أقرب قسم طوارئ.",
        "إذا لم تتمكن من الحضور أو ترغب في إعادة الجدولة، يرجى تقديم إشعار مسبق لمدة 24 ساعة على الأقل؛ وإلا فقد يتم تطبيق رسوم إلغاء.",
        "جميع المراسلات سرية. يرجى عدم الكشف عن موعدك أو معلوماتك الشخصية خارج هذا المكتب.",
        "للمواعيد الشخصية، احضر قبل 15 دقيقة لإكمال أي أوراق ضرورية.",
        "إذا كان لديك تأمين، أحضر تفاصيل بوليصتك (اسم شركة التأمين، رقم البوليصة، معرف المشترك).",
        "للطب عن بُعد، تأكد من وجود اتصال إنترنت مستقر وجهاز متوافق ومساحة هادئة وخاصة.",
      ],
    },
    services: {
      bookAppointment: {
        title: "حجز موعد",
        description: "جدولة موعدك القادم مع أخصائيينا",
      },
      myProfile: {
        title: "ملفي الشخصي",
        description: "عرض وتحديث معلوماتك الشخصية",
      },
      myAppointments: {
        title: "مواعيدي",
        description: "عرض مواعيدك القادمة والسابقة",
      },
      myInvoices: {
        title: "فواتيري",
        description: "الوصول إلى معلومات الفوترة وتاريخ الدفع",
      },
    },
    auth: {
      welcomeBack: "مرحباً بعودتك",
      createAccount: "إنشاء حساب",
      email: "عنوان البريد الإلكتروني",
      password: "كلمة المرور",
      fullName: "الاسم الكامل",
      phone: "رقم الهاتف",
      gender: "الجنس",
      confirmPassword: "تأكيد كلمة المرور",
      emailPlaceholder: "أدخل بريدك الإلكتروني",
      passwordPlaceholder: "أدخل كلمة المرور",
      fullNamePlaceholder: "أدخل اسمك الكامل",
      phonePlaceholder: "أدخل رقم هاتفك",
      createPasswordPlaceholder: "أنشئ كلمة مرور قوية",
      confirmPasswordPlaceholder: "أكد كلمة المرور",
      selectGender: "اختر الجنس",
      male: "ذكر",
      female: "أنثى",
      rememberMe: "تذكرني لمدة 30 يوماً",
      signIn: "تسجيل الدخول",
      signingIn: "جاري تسجيل الدخول...",
      creatingAccount: "جاري إنشاء الحساب...",
      noAccount: "ليس لديك حساب؟ أنشئ واحداً هنا",
      haveAccount: "لديك حساب بالفعل؟ سجل دخولك هنا",
      forgotPassword: "نسيت كلمة المرور؟",
      forgotPasswordTitle: "نسيت كلمة المرور",
      forgotPasswordSubtitle: "أدخل بريدك الإلكتروني لتلقي رابط إعادة تعيين كلمة المرور",
      resetPasswordTitle: "إعادة تعيين كلمة المرور",
      resetPasswordSubtitle: "أدخل كلمة المرور الجديدة",
      enterYourEmail: "أدخل بريدك الإلكتروني",
      sendResetLink: "إرسال رابط إعادة التعيين",
      sending: "جاري الإرسال...",
      backToLogin: "العودة لتسجيل الدخول",
      newPassword: "كلمة المرور الجديدة",
      enterNewPassword: "أدخل كلمة المرور الجديدة",
      confirmNewPassword: "تأكيد كلمة المرور الجديدة",
      resetPassword: "إعادة تعيين كلمة المرور",
      resetting: "جاري إعادة التعيين...",
      passwordMinLength: "يجب أن تكون 8 أحرف على الأقل",
      resetSuccess: "تم إعادة تعيين كلمة المرور بنجاح! جاري التوجيه لتسجيل الدخول...",
      resetEmailSent: "تم إرسال بريد إعادة تعيين كلمة المرور! يرجى التحقق من صندوق الوارد.",
      invalidResetLink: "رابط إعادة التعيين غير صالح",
      passwordsDoNotMatch: "كلمات المرور غير متطابقة",
      passwordTooShort: "يجب أن تكون كلمة المرور 8 أحرف على الأقل",
      resetFailed: "فشل إعادة تعيين كلمة المرور",
      sendEmailFailed: "فشل إرسال بريد إعادة التعيين",
      errorOccurred: "حدث خطأ. يرجى المحاولة مرة أخرى.",
      loading: "جاري التحميل...",
    },
    validation: {
      invalidEmail: "يرجى إدخال عنوان بريد إلكتروني صحيح",
      passwordTooShort: "يجب أن تكون كلمة المرور 6 أحرف على الأقل",
      invalidName: "يجب أن يحتوي الاسم على أحرف فقط ولا يقل عن حرفين",
      invalidPhone: "يرجى إدخال رقم هاتف صحيح",
      weakPassword: "يجب أن تكون كلمة المرور 8 أحرف على الأقل مع أحرف كبيرة وصغيرة ورقم",
      passwordMismatch: "كلمات المرور غير متطابقة",
      validEmail: "عنوان بريد إلكتروني صحيح",
      validName: "اسم صحيح",
      validPhone: "رقم هاتف صحيح",
      passwordsMatch: "كلمات المرور متطابقة",
    },
    messages: {
      logoutSuccess: "تم تسجيل الخروج بنجاح",
      loginSuccess: "مرحباً بعودتك! تم تسجيل الدخول بنجاح",
      loginFailed: "فشل تسجيل الدخول",
      signupSuccess: "تم التسجيل بنجاح! يرجى تسجيل الدخول باستخدام بياناتك",
      signupFailed: "فشل التسجيل",
      fixErrors: "يرجى إصلاح الأخطاء قبل الإرسال",
      selectGender: "يرجى اختيار الجنس",
    },
    wizard: {
      bookAppointment: "احجز موعدك",
      selectEvaluationType: "اختر نوع التقييم",
      chooseEvaluationType: "اختر نوع التقييم الذي يناسبك",
      evaluationType: "نوع التقييم",
      chooseYourEvaluationType: "اختر نوع التقييم...",
      schoolEvaluation: "تقييم مدرسي",
      fullPackageEvaluation: "تقييم الحزمة الكاملة",
      alreadyActive: "(نشط بالفعل)",
      singleSession: "جلسة واحدة",
      continue: "متابعة ←",
      requestEvaluation: "طلب التقييم",
      scheduleAppointment: "جدولة موعدك",
      selectPreferredDateTime: "اختر التاريخ والوقت المفضل وقدم التفاصيل",
      selectDay: "اختر اليوم",
      chooseDate: "اختر تاريخاً",
      selectTime: "اختر الوقت",
      chooseTime: "اختر وقتاً",
      selectedTime: "الوقت المحدد:",
      description: "الوصف",
      descriptionPlaceholder: "يرجى وصف احتياجاتك أو أي متطلبات خاصة...",
      selectServices: "اختر الخدمات",
      chooseServices: "اختر خدماتك...",
      selectedServicesTotal: "إجمالي الخدمات المحددة:",
      back: "→ رجوع",
      wordDocument: "مستند وورد",
      reviewEditDocument: "مراجعة وتحرير المستند",
      reviewCustomizeDocument: "راجع وخصص مستند خطة العلاج الخاصة بك",
      proceedToPayment: "← المتابعة للدفع",
      payment: "الدفع",
      completePayment: "إتمام الدفع",
      securePaymentProcessing: "معالجة دفع آمنة لموعدك",
      paymentSummary: "ملخص الدفع",
      fullProgramTotal: "إجمالي البرنامج الكامل:",
      initialPaymentToday: "الدفعة الأولى (اليوم):",
      remainingAfterConsultation: "المتبقي (بعد الاستشارة):",
      payingNow: "الدفع الآن:",
      paymentNote: "ستكمل الدفع المتبقي بعد استشارتك مع الطبيب.",
      programFee: "رسوم البرنامج:",
      additionalServices: "خدمات إضافية:",
      totalAmount: "المبلغ الإجمالي:",
      completePaymentButton: "💳 إتمام الدفع",
      processing: "جاري المعالجة...",
      securePayment: "معالجة دفع آمنة • مشفرة بـ SSL",
      complete: "مكتمل",
      congratulations: "تهانينا!",
      appointmentBooked: "تم حجز موعدك بنجاح في مركز ركن الواثقون للتأهيل.",
      schoolEvaluationAssigned: " تم تعيينك في برنامج التقييم المدرسي.",
      serviceAssignments: "تعيينات الخدمة",
      assignedToServices: "تم تعيينك تلقائياً في {count} خدمة/خدمات.",
      whatsNext: "ما التالي؟",
      nextSteps: [
        "• ستتلقى بريداً إلكترونياً للتأكيد قريباً",
        "• سيتصل بك فريقنا قبل 24 ساعة من موعدك",
        "• يرجى الوصول قبل 15 دقيقة",
        "• يمكنك الآن الوصول إلى بوابة التقييم المدرسي",
        "• يمكنك عرض تعيينات الخدمة في بوابات الأقسام المعنية",
      ],
      validation: {
        selectEvaluationType: "يرجى اختيار نوع التقييم",
        selectDate: "يرجى اختيار التاريخ",
        selectTime: "يرجى اختيار الوقت",
        provideDescription: "يرجى تقديم وصف",
        selectAtLeastOneService: "يرجى اختيار خدمة واحدة على الأقل",
      },
    },
    profile: {
      title: "ملف الطالب",
      loading: "جاري تحميل الملف الشخصي...",
      error: "خطأ في تحميل الملف الشخصي",
      noData: "لا توجد بيانات للملف الشخصي",
      personalInfo: "المعلومات الشخصية",
      medicalInfo: "المعلومات الطبية",
      programs: "البرامج",
      schools: "المدارس",
      fullProgram: "البرنامج الكامل",
      singleProgram: "الجلسات الفردية",
      name: "الاسم",
      email: "البريد الإلكتروني",
      phone: "الهاتف",
      gender: "الجنس",
      dateOfBirth: "تاريخ الميلاد",
      address: "العنوان",
      emergencyContact: "جهة الاتصال في حالات الطوارئ",
      medicalHistory: "التاريخ الطبي",
      allergies: "الحساسية",
      medications: "الأدوية الحالية",
      lastVisit: "آخر زيارة",
      nextAppointment: "الموعد القادم",
      programName: "البرنامج",
      upcomingEvaluation: "جلسة تقييم قادمة",
      missedEvaluation: "جلسة تقييم فائتة",
      evaluationScheduled: "تم جدولة جلسة التقييم الخاصة بك",
      arriveEarly: "يرجى الوصول قبل 15 دقيقة من موعدك. ستساعدنا هذه الجلسة في تقييم احتياجاتك وإنشاء برنامج شخصي لك.",
      missedSession: "لقد فوت جلسة التقييم الخاصة بك",
      contactReschedule: "يرجى الاتصال بنا لإعادة جدولة جلسة التقييم الخاصة بك. هذا مهم لبدء برنامجك الشخصي.",
      programActive: "برنامجك نشط الآن!",
      accessFiles: "يمكنك الآن الوصول إلى جميع ملفاتك وتتبع تقدمك. تم إكمال جلسة التقييم الخاصة بك في",
      initialEvaluation: "التقييم الأولي:",
      programEnded: "انتهى هذا البرنامج",
      subscriptionEnded: "انتهت اشتراك برنامجك في",
      stillAccess: "لا يزال بإمكانك الوصول إلى ملفاتك وتاريخ التقدم. تم إكمال التقييم الأولي الخاص بك في",
      files: "ملفات",
      departments: "أقسام",
      plans: "خطط",
      exams: "امتحانات",
      viewDocument: "عرض المستند",
      downloadDocument: "تحميل المستند",
      backToFiles: "العودة إلى الملفات",
      tryAgain: "حاول مرة أخرى",
      programName: " برنامج",
      programType: "نوع البرنامج",
      startDate: "تاريخ البداية",
      endDate: "تاريخ النهاية",
      status: "الحالة",
      progress: "التقدم",
      description: "الوصف",
      instructor: "المدرب",
      duration: "المدة",
      sessions: "الجلسات",
      completed: "مكتمل",
      inProgress: "قيد التنفيذ",
      upcoming: "قادم",
      cancelled: "ملغي",
      schoolName: "اسم المدرسة",
      grade: "الصف",
      academicYear: "السنة الأكاديمية",
      subjects: "المواد",
      performance: "الأداء",
      attendance: "الحضور",
      notes: "الملاحظات",
      noPrograms: "لم يتم العثور على برامج",
      noSchools: "لم يتم العثور على مدارس",
      viewDetails: "عرض التفاصيل",
      editProfile: "تعديل الملف الشخصي",
      saveChanges: "حفظ التغييرات",
      cancel: "إلغاء",
      male: "ذكر",
      female: "أنثى",
      other: "آخر",
      active: "نشط",
      inactive: "غير نشط",
      excellent: "ممتاز",
      good: "جيد",
      average: "متوسط",
      needsImprovement: "يحتاج تحسين",
      editProfile: "تعديل الملف الشخصي",
      changePassword: "تغيير كلمة المرور",
      fullProgram: "البرنامج الكامل",
      school: "المدرسة",
      single: "الجلسات الفردية",
      caseStudy: "دراسة الحالة",
      manageProfile: "إدارة ملفك الشخصي وعرض التقييمات وتتبع الجلسات",
      fullName: "الاسم الكامل",
      emailAddress: "البريد الإلكتروني",
      phoneNumber: "رقم الهاتف",
      dateOfBirth: "تاريخ الميلاد",
      address: "العنوان",
      newPassword: "كلمة المرور الجديدة",
      confirmPassword: "تأكيد كلمة المرور",
      enterFullName: "أدخل الاسم الكامل",
      enterEmail: "أدخل عنوان البريد الإلكتروني",
      enterPhone: "أدخل رقم الهاتف",
      enterAddress: "أدخل العنوان",
      enterNewPassword: "أدخل كلمة المرور الجديدة",
      confirmPasswordPlaceholder: "تأكيد كلمة المرور",
      cancel: "إلغاء",
      saveChanges: "حفظ التغييرات",
      savePassword: "حفظ كلمة المرور",
      student: "طالب",
      notProvided: "غير مقدم",
      required: "*",
      at: "في",
      programId: "معرف البرنامج",
      sessionsCompleted: "جلسات مكتملة",
      noPlansAvailable: "لا توجد خطط متاحة",
      yourPlanNotCreated: "لم يتم إنشاء خطتك بعد",
      plansWillBeAvailableAfterCompletion: "ستكون الخطط متاحة بعد اكتمال برنامجك",
      plansWillBeAvailableAfterAllAppointments: "ستكون الخطط متاحة بعد اكتمال جميع المواعيد",
      plansNotAvailableForCancelled: "الخطط غير متاحة للبرامج الملغاة",
      appointments: "المواعيد",
      schoolPlans: "الخطط المدرسية",
      modified: "تم التعديل",
      noSchoolProgramsYet: "ليس لديك أي برامج مدرسية بعد.",
      programScheduledUpcoming: "البرنامج مجدول - الموعد القادم",
      programCancelledMissed: "البرنامج ملغي - الموعد الأول فات",
      programCompletedAllFinished: "البرنامج مكتمل - جميع المواعيد انتهت",
      programActiveNextUpcoming: "البرنامج نشط - الموعد التالي قادم",
      programActiveNextReady: "البرنامج نشط - الموعد التالي جاهز",
      programActiveInProgress: "البرنامج نشط - قيد التقدم",
      programStatusUnknown: "حالة البرنامج غير معروفة",
      noAppointmentsFound: "لم يتم العثور على مواعيد",
      invalidAppointmentDateTime: "تاريخ/وقت الموعد غير صالح",
      missed: "فائت",
      notStarted: "لم يبدأ",
      unknown: "غير معروف",
      backToPrograms: "العودة إلى البرامج",
      assignmentDetails: "تفاصيل التعيين",
      session: "الجلسة",
      assignedDate: "تاريخ التعيين",
      notes: "ملاحظات",
      treatmentPlan: "خطة العلاج",
      lastUpdated: "آخر تحديث",
      noAssignmentFound: "لم يتم العثور على تعيين لهذا القسم",
      noTreatmentPlanAvailable: "لا توجد خطة علاج متاحة بعد",
      notAssigned: "غير معين",
      noSingleProgramsYet: "ليس لديك أي مواعيد برنامج فردي بعد.",
      of: "من",
      invalidDate: "تاريخ غير صالح",
      invalidTime: "وقت غير صالح",
      noTime: "لا يوجد وقت",
      failedToDownload: "فشل تنزيل الملف. يرجى المحاولة مرة أخرى.",
      schoolProgram: "البرنامج المدرسي",
      openDriveFolder: "افتح مجلد Drive", // Added Arabic translation for drive link button
      noMediaYet: "لا توجد وسائط متاحة بعد", // Added Arabic translation for no media placeholder
      failedToLoadPrograms: "فشل تحميل البرامج الفردية. يرجى المحاولة مرة أخرى.",
      abaTherapy: "ABA",
      speechTherapy: "علاج النطق",
      physicalTherapy: "العلاج الطبيعي",
      occupationalTherapy: "العلاج الوظيفي",
      specialEducation: "التربية الخاصة",
      paidOnline: "مدفوع عبر الإنترنت",
      paidAtCenter: "مدفوع في المركز",
      paidViaBankTransfer: "مدفوع عبر التحويل البنكي",
      bankTransferPending: "التحويل البنكي قيد المراجعة",
      bankTransferRejected: "التحويل البنكي مرفوض",
      pendingOnlinePayment: "دفع إلكتروني معلق",
      pendingPaymentAtCenter: "دفع معلق في المركز",
      paidOnlineViaWebsite: "مدفوع عبر الإنترنت عبر الموقع",
      paidCashAtCenter: "مدفوع نقداً في المركز",
      paidViaBankTransferConfirmed: "مدفوع عبر التحويل البنكي (مؤكد)",
      bankTransferPendingMessage: "يتم مراجعة تحويلك البنكي. سنخطرك بمجرد التأكيد.",
      bankTransferRejectedMessage: "تم رفض دفعتك عبر التحويل البنكي. يرجى الاتصال بالدعم.",
      waitingForOnlinePayment: "في انتظار الدفع عبر الإنترنت",
      paymentDueAtCenter: "الدفع مستحق عند وصول العميل إلى المركز",
      completedAt: "مكتمل:",
      departmentsCount: "أقسام",
    },
  },
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState("ar")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language")
    if (savedLanguage && (savedLanguage === "en" || savedLanguage === "ar")) {
      setLanguage(savedLanguage)
    } else {
      setLanguage("ar")
      localStorage.setItem("language", "ar")
    }
  }, [])

  const toggleLanguage = () => {
    const newLanguage = language === "en" ? "ar" : "en"
    setLanguage(newLanguage)
    localStorage.setItem("language", newLanguage)
  }

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        toggleLanguage,
        translations,
      }}
    >
      {children}
    </LanguageContext.Provider>
  )
}
